import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from . import config


class CompatRow(dict):
    """Dictionary row that retains sqlite.Row's integer-index access."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


def _postgres_row(cursor):
    description = cursor.description
    if description is None:
        # Psycopg invokes the factory for commands such as CREATE/UPDATE too.
        # Match psycopg.rows.dict_row's no-result behavior for those commands.
        from psycopg.rows import no_result
        return no_result
    columns = [column.name for column in description]

    def make_row(values):
        return CompatRow(zip(columns, values))

    return make_row


def _postgres_sql(sql):
    """Translate the project's DB-API qmark parameters for Psycopg."""
    return sql.replace('?', '%s')


class PostgresConnection:
    def __init__(self, raw):
        self.raw = raw

    def execute(self, sql, params=()):
        return self.raw.execute(_postgres_sql(sql), params)

    def executemany(self, sql, params):
        with self.raw.cursor() as cursor:
            cursor.executemany(_postgres_sql(sql), params)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()


def using_postgres():
    return bool(config.DATABASE_URL)


def now():
    return datetime.now(timezone.utc).isoformat()


def encode(obj):
    return json.dumps(obj, ensure_ascii=False, allow_nan=False, default=str)


@contextmanager
def connection():
    if using_postgres():
        try:
            import psycopg
        except ImportError as exc:
            raise RuntimeError('PostgreSQL is configured but psycopg is not installed.') from exc
        raw = psycopg.connect(
            config.DATABASE_URL,
            row_factory=_postgres_row,
            connect_timeout=15,
            prepare_threshold=None,
        )
        conn = PostgresConnection(raw)
    else:
        config.DATA_DIR.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(config.DB_PATH, timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute('PRAGMA foreign_keys=ON')
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _schema_statements(postgres):
    identity = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if postgres else 'INTEGER PRIMARY KEY'
    artifact = 'BYTEA' if postgres else 'BLOB'
    return [
        '''CREATE TABLE IF NOT EXISTS datasets (
            id TEXT PRIMARY KEY, name TEXT NOT NULL, source TEXT, created_at TEXT, rows INTEGER,
            accounts INTEGER, time_kind TEXT, min_time DOUBLE PRECISION, max_time DOUBLE PRECISION, quality TEXT)''',
        '''CREATE TABLE IF NOT EXISTS transactions (
            dataset_id TEXT REFERENCES datasets(id) ON DELETE CASCADE, id TEXT, sender TEXT,
            receiver TEXT, time DOUBLE PRECISION, timestamp TEXT, amount TEXT, currency TEXT,
            received TEXT, receiving_currency TEXT, payment_format TEXT, source_row INTEGER,
            device_id TEXT, PRIMARY KEY(dataset_id,id))''',
        'CREATE INDEX IF NOT EXISTS tx_time ON transactions(dataset_id,time,id)',
        'CREATE INDEX IF NOT EXISTS tx_sender ON transactions(dataset_id,sender,time)',
        'CREATE INDEX IF NOT EXISTS tx_receiver ON transactions(dataset_id,receiver,time)',
        '''CREATE TABLE IF NOT EXISTS labels (
            dataset_id TEXT REFERENCES datasets(id) ON DELETE CASCADE, entity_type TEXT,
            entity_id TEXT, label INTEGER, typology TEXT, PRIMARY KEY(dataset_id,entity_type,entity_id))''',
        '''CREATE TABLE IF NOT EXISTS jobs (
            id TEXT PRIMARY KEY, kind TEXT, status TEXT, progress INTEGER, message TEXT,
            created_at TEXT, updated_at TEXT, result TEXT)''',
        '''CREATE TABLE IF NOT EXISTS runs (
            id TEXT PRIMARY KEY, dataset_id TEXT REFERENCES datasets(id), created_at TEXT,
            config TEXT, summary TEXT)''',
        '''CREATE TABLE IF NOT EXISTS alerts (
            id TEXT PRIMARY KEY, run_id TEXT REFERENCES runs(id), dataset_id TEXT,
            pattern TEXT, severity TEXT, score DOUBLE PRECISION, title TEXT, explanation TEXT,
            accounts TEXT, transaction_ids TEXT, evidence TEXT, status TEXT DEFAULT 'New')''',
        'CREATE INDEX IF NOT EXISTS alert_run ON alerts(run_id,severity)',
        f'''CREATE TABLE IF NOT EXISTS notes (
            id {identity}, alert_id TEXT REFERENCES alerts(id), body TEXT, created_at TEXT)''',
        f'''CREATE TABLE IF NOT EXISTS audit (
            id {identity}, event TEXT, entity_id TEXT, details TEXT, created_at TEXT)''',
        f'''CREATE TABLE IF NOT EXISTS models (
            id TEXT PRIMARY KEY, dataset_id TEXT, created_at TEXT, kind TEXT, metadata TEXT,
            artifact {artifact})''',
    ]


def init_db(recover_jobs=False):
    postgres = using_postgres()
    with connection() as c:
        if not postgres:
            c.execute('PRAGMA journal_mode=WAL')
        for statement in _schema_statements(postgres):
            c.execute(statement)
        # Upgrade databases created by the original filesystem-model release.
        if postgres:
            c.execute('ALTER TABLE models ADD COLUMN IF NOT EXISTS artifact BYTEA')
        else:
            columns = {row[1] for row in c.execute('PRAGMA table_info(models)')}
            if 'artifact' not in columns:
                c.execute('ALTER TABLE models ADD COLUMN artifact BLOB')
        if recover_jobs:
            c.execute(
                "UPDATE jobs SET status='interrupted',message='Server restarted. Please run again.',updated_at=? "
                "WHERE status IN ('queued','running')",
                (now(),),
            )


def audit(c, event, entity_id, details):
    c.execute(
        'INSERT INTO audit(event,entity_id,details,created_at) VALUES(?,?,?,?)',
        (event, entity_id, encode(details), now()),
    )


def dataset_dict(row):
    d = dict(row)
    d['quality'] = json.loads(d['quality'])
    return d


def alert_dict(row):
    d = dict(row)
    for field in ('accounts', 'transaction_ids', 'evidence'):
        d[field] = json.loads(d[field])
    return d
