import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowDownToLine,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,ChevronDown,Database,FileText,Filter,FolderOpen,GitBranch,Layers,Loader2,LockKeyhole,Network,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Upload,Users,X,AlertTriangle,Copy,CheckCircle2,Clock3,ExternalLink} from 'lucide-react';
import Graph from './Graph';
import {API,request,post,download,Dataset,Alert,Transaction,number,human,date} from './api';

const pages=[['overview','Investigation overview',Layers],['workspace','Network & flows',Network],['accounts','Account dossiers',Users],['datasets','Datasets & analysis',Database],['models','Models & evaluation',Activity],['audit','Evidence & audit',BookOpen]] as const;
const patterns=['fan_in','fan_out','pass_through','cycle','burst','dormant','shared_device'];
const shortId=(id:string)=>id.length>28?id.slice(0,13)+'…'+id.slice(-10):id;
const emptyRows:Transaction[]=[];

function Badge({children,tone=''}:{children:React.ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
function SectionTitle({n,title,children}:{n:string;title:string;children?:React.ReactNode}){return <div className="section-title"><span><i>{n}</i> {title}</span>{children}</div>}
function Empty({title,body,children}:{title:string;body:string;children?:React.ReactNode}){return <div className="empty"><GitBranch size={32} strokeWidth={1.3}/><h3>{title}</h3><p>{body}</p>{children}</div>}
function TransactionTable({rows,kind,onAccount}:{rows:Transaction[];kind:string;onAccount:(a:string)=>void}){
  return <div className="table-scroll"><table><thead><tr><th>{kind==='step'?'Simulation step':'Source timestamp'}</th><th>Transaction reference</th><th>Origin account</th><th>Destination account</th><th className="right">Amount / currency</th><th>Format</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono nowrap">{r.timestamp?r.timestamp.replace('T',' ').slice(0,19):`Step ${r.time}`}</td><td className="mono" title={r.id}>{shortId(r.id)}</td><td><button className="text-link" title={r.sender} onClick={()=>onAccount(r.sender)}>{shortId(r.sender)}</button></td><td><button className="text-link" title={r.receiver} onClick={()=>onAccount(r.receiver)}>{shortId(r.receiver)}</button></td><td className="amount right">{Number(r.amount).toLocaleString(undefined,{maximumFractionDigits:4})} <small>{r.currency||'Unspecified'}</small></td><td>{r.payment_format||'Not supplied'}</td></tr>)}</tbody></table>{!rows.length&&<p className="table-empty">No transactions match this view.</p>}</div>
}

export default function App(){
  const [page,setPage]=useState('overview');const [datasets,setDatasets]=useState<Dataset[]>([]);const [datasetId,setDatasetId]=useState('');
  const [runs,setRuns]=useState<any[]>([]);const [runId,setRunId]=useState('');const [alerts,setAlerts]=useState<Alert[]>([]);const [alertTotal,setAlertTotal]=useState(0);
  const [selected,setSelected]=useState<Alert|null>(null);const [jobs,setJobs]=useState<any[]>([]);const [models,setModels]=useState<any[]>([]);const [audit,setAudit]=useState<any[]>([]);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(false);const [refresh,setRefresh]=useState(0);
  const [patternFilter,setPatternFilter]=useState('');const [statusFilter,setStatusFilter]=useState('');const [query,setQuery]=useState('');const [searchInput,setSearchInput]=useState('');
  const [account,setAccount]=useState('');const [accountData,setAccountData]=useState<any>(null);const [accountList,setAccountList]=useState<any[]>([]);
  const [txPage,setTxPage]=useState(0);const [transactions,setTransactions]=useState<{items:Transaction[];total:number}>({items:[],total:0});
  const [graphRows,setGraphRows]=useState<Transaction[]>(emptyRows);const [graphLimited,setGraphLimited]=useState(false);
  const [sources,setSources]=useState<any[]>([]);const [importRows,setImportRows]=useState(25000);const [note,setNote]=useState('');
  const [windowSize,setWindowSize]=useState(900);const [minPeers,setMinPeers]=useState(5);const [passRatio,setPassRatio]=useState(.8);const [dormantDays,setDormantDays]=useState(90);const [burstCount,setBurstCount]=useState(8);
  const [enabled,setEnabled]=useState(patterns);const [useMl,setUseMl]=useState(false);const [start,setStart]=useState('');const [end,setEnd]=useState('');
  const [connectionOpen,setConnectionOpen]=useState(false);const [apiKey,setApiKey]=useState(sessionStorage.getItem('mulegraph-key')||'');
  const [sideOpen,setSideOpen]=useState(false);const [submitting,setSubmitting]=useState(false);const uploadRef=useRef<HTMLInputElement>(null);const previousJobs=useRef<Record<string,string>>({});
  const ds=datasets.find(d=>d.id===datasetId);const run=runs.find(r=>r.id===runId&&r.dataset_id===datasetId)||runs.find(r=>r.dataset_id===datasetId);const summary=run?.summary;const busy=submitting||jobs.some(j=>['queued','running'].includes(j.status));
  const reload=()=>setRefresh(r=>r+1);const fail=(e:unknown)=>setError(e instanceof Error?e.message:String(e));
  const navigate=(p:string)=>{setPage(p);setSideOpen(false);window.scrollTo({top:0,behavior:'instant'})};
  const loadDatasets=useCallback(async()=>{try{const data=await request<Dataset[]>('/datasets');setDatasets(data);setDatasetId(id=>data.some(d=>d.id===id)?id:(data.find(d=>d.source==='illustrative_demo')?.id||data[0]?.id||''));setSources(await request('/sources'));}catch(e){fail(e)}},[]);
  useEffect(()=>{loadDatasets()},[loadDatasets,refresh]);
  useEffect(()=>{
    let cancelled=false;
    const poll=async()=>{try{const data=await request<any[]>('/jobs');if(cancelled)return;setJobs(data);
      for(const j of data){if(previousJobs.current[j.id]&&previousJobs.current[j.id]!==j.status&&['completed','failed','interrupted'].includes(j.status)){
        if(j.status==='completed'){setNotice(`${human(j.kind)} completed`);reload();if(j.result?.dataset_id&&['demo','import','upload'].includes(j.kind))setDatasetId(j.result.dataset_id)}else setError(j.message);
      }previousJobs.current[j.id]=j.status;}
    }catch(e){if(!cancelled)fail(e)}};
    poll();const timer=setInterval(poll,2500);return()=>{cancelled=true;clearInterval(timer)};
  },[refresh]);
  useEffect(()=>{setSelected(null);setAccount('');setRunId('');setStart('');setEnd('');setTxPage(0);setWindowSize(ds?.time_kind==='step'?5:900)},[datasetId]);
  useEffect(()=>{
    if(!datasetId)return;let active=true;setLoading(true);
    Promise.all([request('/runs?dataset_id='+datasetId),request('/models?dataset_id='+datasetId),request('/accounts?dataset_id='+datasetId),request('/audit')]).then(([r,m,a,u])=>{if(active){setRuns(r);setModels(m);setAccountList(a);setAudit(u)}}).catch(fail).finally(()=>{if(active)setLoading(false)});
    return()=>{active=false};
  },[datasetId,refresh]);
  useEffect(()=>{
    if(!datasetId)return;let active=true;
    const params=new URLSearchParams({dataset_id:datasetId,limit:'500',q:query});if(runId)params.set('run_id',runId);if(patternFilter)params.set('pattern',patternFilter);if(statusFilter)params.set('status',statusFilter);
    request('/alerts?'+params).then(d=>{if(active){setAlerts(d.items);setAlertTotal(d.total)}}).catch(fail);return()=>{active=false};
  },[datasetId,runId,patternFilter,statusFilter,query,refresh]);
  useEffect(()=>{
    if(!datasetId)return;let active=true;
    request(`/transactions?dataset_id=${datasetId}&offset=${txPage*15}&limit=15&q=${encodeURIComponent(query)}`).then(d=>{if(active)setTransactions(d)}).catch(fail);return()=>{active=false};
  },[datasetId,txPage,query,refresh]);
  useEffect(()=>{
    if(!datasetId)return;let active=true;
    const focus=selected?.dataset_id===datasetId?selected.id:(!account&&alerts[0]?.dataset_id===datasetId?alerts[0].id:undefined);
    request(`/graph?dataset_id=${datasetId}&limit=45${focus?'&alert_id='+focus:account?'&account='+encodeURIComponent(account):''}`).then(d=>{if(active){setGraphRows(d.edges);setGraphLimited(d.limited)}}).catch(fail);return()=>{active=false};
  },[datasetId,selected?.id,alerts[0]?.id,account,refresh]);
  useEffect(()=>{
    if(!datasetId||!account){setAccountData(null);return}let active=true;
    request(`/accounts/detail?dataset_id=${datasetId}&account=${encodeURIComponent(account)}`).then(d=>{if(active)setAccountData(d)}).catch(fail);return()=>{active=false};
  },[datasetId,account,refresh]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer)},[notice]);
  async function action(path:string,body?:unknown){setError('');setSubmitting(true);try{const data=await post(path,body);if(data.job_id)previousJobs.current[data.job_id]='queued';setNotice('Job queued. Progress appears below.');reload()}catch(e){fail(e)}finally{setSubmitting(false)}}
  async function openAlert(a:Alert){try{const d=await request<Alert>('/alerts/'+a.id);setSelected(d);setNote('');setAccount('');navigate('workspace')}catch(e){fail(e)}}
  function inspectAccount(id:string){setAccount(id);navigate('accounts')}
  async function update(status?:string){if(!selected)return;try{setSelected(await request('/alerts/'+selected.id,{method:'PATCH',body:JSON.stringify({status,note:status?'':note})}));setNote('');reload();setNotice('Investigation updated')}catch(e){fail(e)}}
  async function exportEvidence(format:string){if(!selected)return;try{await download(selected.id,format);setNotice('Evidence exported')}catch(e){fail(e)}}
  function boundary(value:string){return value?(ds?.time_kind==='step'?Number(value):Date.parse(value+'Z')/1000):null}
  const analysisBody={dataset_id:datasetId,start:boundary(start),end:boundary(end),window:windowSize,min_peers:minPeers,pass_ratio:passRatio,burst_count:burstCount,dormant_days:dormantDays,patterns:enabled,use_ml:useMl};
  const sourceName=ds?.source==='illustrative_demo'?'Illustrative sandbox':'Synthetic research data';
  const latestModel=models[0]?.metadata;
  const pending=jobs.find(j=>['running','queued'].includes(j.status));

  const alertList=(compact=false)=><div className={'alert-list '+(compact?'compact':'')}>
    {alerts.slice(0,compact?5:500).map(a=><button className={'alert-row '+(selected?.id===a.id?'selected':'')} key={a.id} onClick={()=>openAlert(a)}><span className={'severity-dot '+a.severity.toLowerCase()}/><div><span className="mono tiny">{a.id}</span><strong>{a.title}</strong><span className="muted small">{a.accounts.length} accounts · {a.transaction_ids.length} transactions</span></div><div className="alert-right"><Badge tone={a.severity.toLowerCase()}>{a.severity}</Badge><span className="mono tiny">{a.status}</span></div><ArrowUpRight size={15}/></button>)}
    {!alerts.length&&<Empty title="No alerts in this view" body={run?'Try different filters or analysis thresholds. No alerts is not proof that all activity is safe.':'Run an analysis to generate evidence-led alerts.'}/>}
  </div>;

  return <div className="app-shell">
    <div className="system-strip"><span><b className="live-dot"/> RESEARCH WORKSPACE <i>/</i> HUMAN REVIEW REQUIRED</span><span>{sourceName.toUpperCase()} <i>/</i> V. 1.0</span><button onClick={()=>setConnectionOpen(true)}><LockKeyhole size={11}/> CONNECTION</button></div>
    <header className="main-header"><button className="brand" onClick={()=>navigate('overview')}><span className="brand-mark"><GitBranch size={25}/></span><span>MULEGRAPH<small>FOLLOW THE MONEY. FIND THE CONTEXT.</small></span></button>
      <form className="global-search" onSubmit={e=>{e.preventDefault();setQuery(searchInput);setTxPage(0);navigate('overview')}}><Search size={17}/><input aria-label="Search accounts or transaction IDs" placeholder="Search accounts, transaction IDs, evidence…" value={searchInput} onChange={e=>setSearchInput(e.target.value)}/><kbd>↵</kbd></form>
      <button className="button dark header-action" disabled={!selected} onClick={()=>exportEvidence('json')}><ArrowDownToLine size={15}/> Export evidence</button><button className="profile" title="Connection settings" onClick={()=>setConnectionOpen(true)}>MG</button><button className="mobile-menu icon-btn" aria-label="Toggle navigation" onClick={()=>setSideOpen(!sideOpen)}><Layers size={21}/></button>
    </header>
    <div className="workspace-layout">
      <aside className={'sidebar '+(sideOpen?'open':'')}><div className="sidebar-label mono">WORKSPACE / 01</div><nav>{pages.map(([id,title,Icon],i)=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon size={17}/><span>{title}</span><small>0{i+1}</small></button>)}</nav>
        <div className="sidebar-separator"/><div className="sidebar-label mono">ACTIVE COLLECTION</div><label className="dataset-switch"><Database size={15}/><select aria-label="Active dataset" value={datasetId} onChange={e=>setDatasetId(e.target.value)}>{!datasets.length&&<option value="">No dataset loaded</option>}{datasets.map(d=><option key={d.id} value={d.id}>{d.name} · {number(d.rows)} rows</option>)}</select></label>
        {ds&&<div className="collection-meta"><span>{number(ds.rows)} records</span><span>{number(ds.accounts)} accounts</span><Badge>{ds.time_kind==='step'?'Simulation time':'Source timestamps'}</Badge></div>}
        <div className="sidebar-note"><div className="mini-network"><span/><span/><span/><span/><span/></div><span className="mono tiny">EVIDENCE BEFORE ASSUMPTION.</span><p>Patterns reveal connections.<br/>Context guides decisions.</p></div>
        <div className="sidebar-footer"><ShieldCheck size={15}/><span>Research, not a verdict<small>NO AUTOMATED ACCOUNT ACTIONS</small></span></div>
      </aside>
      <main>
        <div className="page-crumb"><span className="mono">MULEGRAPH / {human(page).toUpperCase()}</span><span className="mono">{ds?ds.name:'START A NEW INVESTIGATION'} {loading&&<Loader2 className="spin" size={12}/>}</span></div>
        {error&&<div className="error-banner" role="alert"><AlertTriangle size={18}/><div><strong>Something needs attention</strong><p>{error==='Failed to fetch'?`Cannot reach the API at ${API}. Start the backend or check deployment and CORS settings.`:error}</p></div><button className="icon-btn" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
        {notice&&<div className="toast" role="status"><CheckCircle2 size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
        {pending&&<div className="job-banner"><Loader2 size={16} className="spin"/><span>{human(pending.kind)} · {pending.message}</span><progress max="100" value={pending.progress}/><span className="mono">{pending.progress}%</span></div>}

        {page==='overview'&&<>
          <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> FINANCIAL NETWORK INTELLIGENCE <i>·</i> CASE WORKSPACE</div><h1>Every transaction<br/>has a <em>story.</em></h1><p>Trace the connections. Surface the unusual.<br/>Turn complex money flows into evidence you can explain.</p><div className="hero-actions"><button className="button dark" onClick={()=>navigate('datasets')}>{ds?<SlidersHorizontal size={15}/>:<Plus size={15}/>} {ds?'Configure analysis':'Start an investigation'}<ArrowUpRight size={15}/></button><span className="mono tiny">PATTERNS. CONTEXT. CLARITY.</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-circle"/><div className="art-grid"/><div className="art-card"><span className="mono tiny">FIG. 01 / CONNECTED EVIDENCE</span><svg viewBox="0 0 300 180"><path d="M35 100 Q90 10 155 80 T265 65 M35 100 Q100 170 155 80 L225 150 M155 80 L115 25"/><g>{[[35,100],[155,80],[265,65],[225,150],[115,25]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={i===1?18:9}/>{i===1&&<circle cx={x} cy={y} r="5"/>}</g>)}</g></svg><div className="art-footer"><span>ORIGIN</span><span>CONNECTION</span><span>CONTEXT</span></div></div><span className="art-tag mono">NOTHING EXISTS<br/>IN ISOLATION.</span></div></section>
          <div className="metric-grid"><Metric n="01" label="TRANSACTIONS LOADED" value={number(ds?.rows)} detail={ds?.quality.truncated?'Source-row subset · not full dataset':'Current research collection'} icon={<Database size={17}/>}/><Metric n="02" label="ACCOUNTS FLAGGED" value={number(summary?.flagged_accounts)} detail="Require analyst review" icon={<Users size={17}/>}/><Metric n="03" label="PATTERN ALERTS" value={number(summary?.alerts)} detail={summary?`${Object.keys(summary.patterns).length} pattern families`:'Run an analysis to begin'} accent icon={<GitBranch size={17}/>}/><Metric n="04" label="ANALYSIS RUNTIME" value={summary?summary.seconds+'s':'—'} detail="Measured backend execution" icon={<Clock3 size={17}/>}/></div>
          {!ds?<section className="panel"><Empty title="Your investigation begins with data" body="Import one of your prepared datasets, or explore a clearly labeled illustrative sandbox. Nothing is fabricated behind the interface."><div className="button-row"><button className="button dark" disabled={busy} onClick={()=>action('/datasets/demo')}><Sparkles size={15}/> Load illustrative sandbox</button><button className="button" onClick={()=>navigate('datasets')}>Import your data <ArrowRight size={15}/></button></div></Empty></section>:<>
          <div className="overview-grid"><section className="panel"><SectionTitle n="01" title="PRIORITY QUEUE"><button className="text-link" onClick={()=>navigate('workspace')}>View all {alertTotal} <ArrowUpRight size={13}/></button></SectionTitle>{alertList(true)}</section><section className="panel pattern-panel"><SectionTitle n="02" title="SIGNAL COMPOSITION"/><div className="pattern-summary"><span className="serif">{summary?.alerts||0}</span><div className="mono tiny">ALERTS<br/>IN THIS RUN</div></div>{Object.entries(summary?.patterns||{}).map(([p,n])=><button className="pattern-bar" key={p} onClick={()=>{setPatternFilter(p);navigate('workspace')}}><span>{human(p)}</span><b>{String(n)}</b><i style={{width:Math.max(3,Number(n)/Math.max(1,summary.alerts)*100)+'%'}}/></button>)}{!summary&&<p className="muted">No analysis results yet.</p>}<p className="disclaimer">A signal is a starting point.<br/>It is not a finding of wrongdoing.</p></section></div>
          <section className="panel graph-preview"><SectionTitle n="03" title="TRANSACTION TOPOLOGY"><Badge>{graphLimited?'Focused view · limited':'Focused view'}</Badge></SectionTitle><Graph rows={graphRows} kind={ds.time_kind} onSelect={inspectAccount}/></section>
          <section className="panel"><SectionTitle n="04" title="TRANSACTION RECORD"><span className="mono tiny">{query?'FILTERED / '+query:'SOURCE VALUES PRESERVED'}</span></SectionTitle><TransactionTable rows={transactions.items} kind={ds.time_kind} onAccount={inspectAccount}/><div className="table-footer"><span className="mono tiny">{number(transactions.total)} MATCHING RECORDS · PAGE {txPage+1}</span><div className="button-row"><button className="icon-btn" aria-label="Previous transactions" disabled={!txPage} onClick={()=>setTxPage(p=>p-1)}><ChevronLeft size={16}/></button><button className="icon-btn" aria-label="Next transactions" disabled={(txPage+1)*15>=transactions.total} onClick={()=>setTxPage(p=>p+1)}><ChevronRight size={16}/></button></div></div></section></>}
        </>}

        {page==='workspace'&&<>
          <PageHeading overline="02 / FOLLOW THE CONNECTIONS" title="Network" italic="& flows" description="Inspect the path. Read the evidence. Make an informed decision."/>
          <div className="filter-bar"><Filter size={16}/><select aria-label="Pattern filter" value={patternFilter} onChange={e=>setPatternFilter(e.target.value)}><option value="">All patterns</option>{[...patterns,'ml_anomaly'].map(p=><option key={p} value={p}>{human(p)}</option>)}</select><select aria-label="Status filter" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All statuses</option>{['New','Reviewing','Escalated','Closed'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Analysis run" value={runId||run?.id||''} onChange={e=>{setRunId(e.target.value);setSelected(null)}}>{runs.map(r=><option key={r.id} value={r.id}>Run {r.id.slice(0,6)} · {r.summary.alerts} alerts</option>)}</select><button className="text-link" onClick={()=>{setPatternFilter('');setStatusFilter('');setQuery('');setSearchInput('')}}>Reset filters</button></div>
          <div className="investigation-grid"><section className="panel queue"><SectionTitle n="A" title={`ALERTS / ${alertTotal}`}/>{alertList()}</section><section className="panel investigation-graph"><SectionTitle n="B" title={selected?.title.toUpperCase()||'NETWORK EXPLORER'}><Badge>{graphLimited?'Limited view':'Evidence view'}</Badge></SectionTitle><Graph rows={graphRows} kind={ds?.time_kind} onSelect={inspectAccount}/>{selected&&<div className="graph-bottom mono">{selected.id} · {selected.accounts.length} ACCOUNTS · {selected.transaction_ids.length} TRANSACTIONS</div>}</section></div>
          {selected?<section className="panel evidence"><SectionTitle n="C" title="WHY THIS WAS FLAGGED"><Badge tone={selected.severity.toLowerCase()}>{selected.severity} priority</Badge></SectionTitle><div className="evidence-grid"><div><h2>{selected.title}</h2><p>{selected.explanation}</p><div className="evidence-values">{Object.entries(selected.evidence).filter(([k,v])=>!['start','end','amounts_by_currency','score_meaning'].includes(k)&&typeof v!=='object').map(([k,v])=><div key={k}><span className="mono tiny">{human(k).toUpperCase()}</span><strong>{String(v)}</strong></div>)}</div><p className="disclaimer">{selected.evidence.score_meaning||'Rule-based priority, not a probability of fraud.'}</p><div className="button-row"><button className="button" onClick={()=>exportEvidence('json')}><ArrowDownToLine size={14}/> Evidence JSON</button><button className="button" onClick={()=>exportEvidence('csv')}><FileText size={14}/> Transactions CSV</button></div></div><div className="notes-panel"><label className="field">Investigation status<select value={selected.status} onChange={e=>update(e.target.value)}>{['New','Reviewing','Escalated','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Analyst note<textarea placeholder="Record context, questions, or your next step…" value={note} maxLength={5000} onChange={e=>setNote(e.target.value)}/></label><button className="button dark" disabled={!note.trim()} onClick={()=>update()}>Save note <ArrowRight size={14}/></button><div className="notes-list">{selected.notes?.map(n=><div key={n.id}><p>{n.body}</p><span className="mono tiny">{n.created_at.slice(0,19).replace('T',' ')} UTC</span></div>)}</div></div></div><TransactionTable rows={selected.transactions||emptyRows} kind={ds?.time_kind||'timestamp'} onAccount={inspectAccount}/></section>:<div className="hint"><MouseHint/> Open an alert to inspect its rule, supporting transactions, and investigation notes.</div>}
          {summary?.limits&&<p className="disclaimer">Analysis limits: {summary.limits.cycle_search_limits}. {summary.limits.alert_limit_reached?'Alert cap reached. Narrow the window for further coverage.':''} {summary.limits.cycle_search_budget_reached?'Cycle search budget reached; results are partial.':''}</p>}
        </>}

        {page==='accounts'&&<>
          <PageHeading overline="03 / ENTITY CONTEXT" title="Account" italic="dossiers" description="Observed activity, connected alerts, and the context behind each account."/>
          <div className="account-layout"><section className="panel account-directory"><SectionTitle n="01" title="ACCOUNT DIRECTORY"/><form className="inline-search" onSubmit={async e=>{e.preventDefault();try{setAccountList(await request('/accounts?dataset_id='+datasetId+'&q='+encodeURIComponent(account)))}catch(err){fail(err)}}}><Search size={15}/><input aria-label="Find account" value={account} placeholder="Find an account…" onChange={e=>setAccount(e.target.value)}/></form>{accountList.map(a=><button className={'account-row '+(account===a.account?'selected':'')} onClick={()=>setAccount(a.account)} key={a.account}><span className="account-symbol"><Users size={15}/></span><span title={a.account}>{shortId(a.account)}<small>{number(a.activity)} recorded interactions</small></span><ArrowUpRight size={13}/></button>)}</section><section className="panel account-detail">{accountData?<><SectionTitle n="02" title="OBSERVED ACCOUNT"/><div className="account-heading"><div className="account-symbol large"><Users size={26}/></div><h2>{accountData.account}</h2><button className="icon-btn" title="Copy account identifier" onClick={()=>navigator.clipboard.writeText(accountData.account).then(()=>setNotice('Account ID copied')).catch(fail)}><Copy size={16}/></button></div><div className="account-facts"><div><strong>{number(accountData.transactions.total)}</strong><span>Recorded transactions</span></div><div><strong>{number(accountData.alerts.length)}</strong><span>Linked alerts across runs</span></div></div><p className="disclaimer padded">Identity and KYC details are not supplied. This dossier contains observed transaction data only.</p><div className="currency-chips">{accountData.currency_activity.map((c:any,i:number)=><Badge key={i}>{c.currency||'Unspecified'} · {c.direction} {c.count}</Badge>)}</div><div className="linked-alerts">{accountData.alerts.map((a:Alert)=><button className="button" key={a.id} onClick={()=>openAlert(a)}>{a.title}<ArrowUpRight size={13}/></button>)}</div><TransactionTable rows={accountData.transactions.items} kind={ds?.time_kind||'timestamp'} onAccount={inspectAccount}/><p className="disclaimer padded">Showing up to 100 earliest account transactions.</p></>:<Empty title="Select an account" body="Explore its observed activity and linked investigation alerts."/>}</section></div>
        </>}

        {page==='datasets'&&<>
          <PageHeading overline="04 / DATA & DETECTION" title="A foundation" italic="of evidence." description="Import research data, review its limitations, and configure reproducible analyses."/>
          <div className="dataset-cards">{[['ibm','IBM HI-Small','Minute-level timestamps · paid and received amounts'],['samld','SAML-D','Second-level timestamps · pattern labels'],['amlsim','AMLSim 20K','Simulation steps · account-level labels']].map(([id,name,description],i)=><section className="panel source-card" key={id}><span className="mono tiny">SOURCE / 0{i+1}</span><Database size={25}/><h3>{name}</h3><p>{description}</p><Badge>{sources.find(s=>s.id===id)?.available?'Local files available':'Upload required on this server'}</Badge><button className="button" disabled={busy||!sources.find(s=>s.id===id)?.available} onClick={()=>action('/datasets/local',{source:id,limit:importRows})}>Import source <ArrowUpRight size={14}/></button></section>)}</div>
          <section className="panel import-panel"><div><h3>Your data, preserved.</h3><p>Prepared CSV, CSV.GZ, or supported raw source schema. Invalid rows are counted and reported.</p><label className="field inline">Source-row import limit<input type="number" min="100" max="250000" value={importRows} onChange={e=>setImportRows(Number(e.target.value))}/></label><p className="disclaimer">First source rows are imported—not a representative sample. Large files are streamed; browser upload limit is 100 MB.</p></div><div className="button-column"><input hidden ref={uploadRef} type="file" accept=".csv,.gz" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setSubmitting(true);try{const form=new FormData();form.append('file',file);const job=await request('/datasets/upload?limit='+importRows,{method:'POST',body:form});previousJobs.current[job.job_id]='queued';reload();setNotice('Upload accepted; validation queued')}catch(err){fail(err)}finally{setSubmitting(false);e.target.value=''}}}/><button className="button dark" disabled={busy} onClick={()=>uploadRef.current?.click()}><Upload size={15}/> Upload CSV</button><button className="button" disabled={busy} onClick={()=>action('/datasets/demo')}><Sparkles size={15}/> Illustrative sandbox</button></div></section>
          {ds&&<><div className="setup-grid"><section className="panel"><SectionTitle n="01" title="COLLECTION QUALITY"/><div className="quality-content"><h2>{ds.name}</h2><div className="quality-row"><span>Accepted / rejected</span><strong>{number(ds.quality.accepted)} / {number(ds.quality.rejected)}</strong></div><div className="quality-row"><span>Observation range</span><strong>{date(ds.min_time,ds.time_kind)}<br/>{date(ds.max_time,ds.time_kind)}</strong></div><div className="quality-row"><span>Labeled entities</span><strong>{number(ds.quality.labeled_entities)}</strong></div><div className="quality-row"><span>Currency coverage</span><strong>{Object.keys(ds.quality.currencies).join(', ')}</strong></div><div className="quality-row"><span>Missing received amount</span><strong>{number(ds.quality.missing.amount_received)}</strong></div><div className="quality-row"><span>Device identifiers</span><strong>{ds.quality.missing.device_id===ds.rows?'Not supplied':`${ds.rows-ds.quality.missing.device_id} rows supplied`}</strong></div><p className="disclaimer">{ds.quality.selection}. {ds.quality.timezone}.</p>{ds.quality.rejected_examples?.length>0&&<details><summary>Rejected row examples</summary><pre>{JSON.stringify(ds.quality.rejected_examples,null,2)}</pre></details>}</div></section>
          <section className="panel"><SectionTitle n="02" title="ANALYSIS CONTROLS"/><div className="analysis-controls"><div className="form-grid"><label className="field">{ds.time_kind==='step'?'Start step':'Start source date/time'}<input type={ds.time_kind==='step'?'number':'datetime-local'} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">{ds.time_kind==='step'?'End step':'End source date/time'}<input type={ds.time_kind==='step'?'number':'datetime-local'} value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field">Window ({ds.time_kind==='step'?'steps':'seconds'})<input type="number" min="1" max="604800" value={windowSize} onChange={e=>setWindowSize(Number(e.target.value))}/></label><label className="field">Minimum counterparties<input type="number" min="3" max="100" value={minPeers} onChange={e=>setMinPeers(Number(e.target.value))}/></label><label className="field">Minimum pass-through ratio<input type="number" step=".05" min=".05" max="1" value={passRatio} onChange={e=>setPassRatio(Number(e.target.value))}/></label><label className="field">Burst transaction count<input type="number" min="3" max="1000" value={burstCount} onChange={e=>setBurstCount(Number(e.target.value))}/></label><label className="field">Observed dormancy days<input type="number" min="1" value={dormantDays} onChange={e=>setDormantDays(Number(e.target.value))} disabled={ds.time_kind==='step'}/></label></div><div className="detector-toggles">{patterns.map(p=>{const unavailable=(p==='shared_device'&&ds.quality.missing.device_id===ds.rows)||(p==='dormant'&&ds.time_kind==='step');return <label key={p} className={unavailable?'unavailable':''}><input type="checkbox" checked={enabled.includes(p)&&!unavailable} disabled={unavailable} onChange={e=>setEnabled(e.target.checked?[...enabled,p]:enabled.filter(x=>x!==p))}/>{human(p)}{unavailable&&<small>Data unavailable</small>}</label>})}</div><label className="ml-toggle"><input type="checkbox" checked={useMl} disabled={!models.length} onChange={e=>setUseMl(e.target.checked)}/><span>Include trained anomaly model<small>{models.length?'Post-training observations only':'Train a model in Models & evaluation first'}</small></span></label><button className="button dark full" disabled={busy||!enabled.length} onClick={()=>action('/analysis',analysisBody)}><GitBranch size={16}/> Run analysis <ArrowRight size={15}/></button><p className="disclaimer">Blank dates use the imported range. Maximum 100,000 rows per analysis by default. All thresholds are research settings, not regulatory limits.</p></div></section></div></>}
        </>}

        {page==='models'&&<>
          <PageHeading overline="05 / MACHINE LEARNING" title="Measure first." italic="Then trust." description="Real training, chronological evaluation, and explicit limits. No invented confidence scores."/>
          {summary?.evaluation&&<section className="panel"><SectionTitle n="R" title="LATEST ANALYSIS / DESCRIPTIVE EVALUATION"/><div className="quality-content"><div className="account-facts"><div><strong>{(summary.evaluation.precision*100).toFixed(2)}%</strong><span>Flagged {summary.evaluation.entity_type} precision</span></div><div><strong>{(summary.evaluation.recall*100).toFixed(2)}%</strong><span>Source-positive recall</span></div><div><strong>{number(summary.evaluation.positive)}</strong><span>Source-positive entities in window</span></div></div><p className="disclaimer">{summary.evaluation.scope}. These are separate from the held-out ML results below.</p></div></section>}
          <section className="panel model-intro"><div><Badge>ISOLATION FOREST + SUPERVISED BASELINE</Badge><h2>Unusual is not the same as unlawful.</h2><p>Train on earlier observations. Select a supervised threshold on validation data. Report performance on a later, untouched test period.</p><div className="split-diagram"><span>70% TRAIN</span><span>15% VALIDATE</span><span>15% TEST</span></div><p className="disclaimer">Equal timestamps stay together. Source labels are targets, never input features. Supervised training requires both classes in every period.</p></div><button className="button dark" disabled={!ds||busy} onClick={()=>action('/models/train',{dataset_id:datasetId,start:boundary(start),end:boundary(end)})}><Sparkles size={16}/> Train models</button></section>
          {latestModel?<><div className="metric-grid">{[['PRECISION',latestModel.test?.precision],['RECALL',latestModel.test?.recall],['F1 SCORE',latestModel.test?.f1],['PR-AUC',latestModel.test?.pr_auc]].map(([label,v],i)=><Metric key={String(label)} n={'0'+(i+1)} label={String(label)} value={typeof v==='number'?v.toFixed(3):'N/A'} detail="Supervised temporal test set"/>)}</div><div className="setup-grid"><section className="panel"><SectionTitle n="01" title="MODEL CARD"/><div className="quality-content"><h3>{latestModel.supervised_status}</h3><p>{latestModel.split}</p>{Object.entries(latestModel.split_counts).map(([k,v])=><div className="quality-row" key={k}><span>{human(k)}</span><strong>{number(Number(v))} records</strong></div>)}<p className="disclaimer">{latestModel.limits}</p>{latestModel.limitations.map((l:string)=><p className="disclaimer" key={l}>— {l}</p>)}</div></section><section className="panel"><SectionTitle n="02" title="EVALUATION EVIDENCE"/><div className="quality-content">{latestModel.test?<><h3>Confusion matrix</h3><p className="muted small">Rows = source labels · Columns = predictions</p><div className="confusion"><span/><span>Normal</span><span>Flagged</span><span>Normal</span><strong>{number(latestModel.test.confusion_matrix[0][0])}</strong><strong>{number(latestModel.test.confusion_matrix[0][1])}</strong><span>Positive</span><strong>{number(latestModel.test.confusion_matrix[1][0])}</strong><strong>{number(latestModel.test.confusion_matrix[1][1])}</strong></div><p className="disclaimer">Positive test prevalence: {(latestModel.test.prevalence*100).toFixed(3)}%. Results apply only to this imported synthetic sample.</p></>:<p>No valid supervised result. This dataset or time window lacks sufficient transaction-level positive and negative labels.</p>}{latestModel.anomaly_test&&<details><summary>Isolation Forest test metrics</summary><pre>{JSON.stringify(latestModel.anomaly_test,null,2)}</pre></details>}<details><summary>Features and model metadata</summary><pre>{JSON.stringify(latestModel,null,2)}</pre></details></div></section></div></>:<section className="panel"><Empty title="No model trained for this collection" body="Training produces a persisted model and a model card. Source datasets with account-only labels can still support unsupervised anomaly detection."/></section>}
        </>}

        {page==='audit'&&<>
          <PageHeading overline="06 / INVESTIGATION RECORD" title="An accountable" italic="paper trail." description="A persistent record of imports, analyses, model training, and review decisions."/>
          <div className="notice-card"><ShieldCheck size={21}/><p>Exports are research evidence bundles—not regulatory SAR filings. This audit log is application-level history, not a certified tamper-proof ledger.</p></div><section className="panel"><SectionTitle n="01" title="RECENT ACTIVITY"><button className="text-link" onClick={reload}><RefreshCw size={13}/> Refresh</button></SectionTitle><div className="audit-list">{audit.map(a=><div className="audit-row" key={a.id}><div className="audit-mark"><Check size={14}/></div><div><strong>{human(a.event.replace('.',' / '))}</strong><span className="mono tiny">{a.entity_id}</span><details><summary>View recorded details</summary><pre>{JSON.stringify(a.details,null,2)}</pre></details></div><span className="mono tiny">{a.created_at.slice(0,19).replace('T',' ')} UTC</span></div>)}{!audit.length&&<Empty title="The record starts here" body="Import data or run an analysis to create the first audit event."/>}</div></section>
          <section className="panel"><SectionTitle n="02" title="BACKGROUND JOBS"/><div className="jobs-list">{jobs.map(j=><div key={j.id}><strong>{human(j.kind)}</strong><Badge tone={j.status==='failed'?'high':''}>{j.status}</Badge><span>{j.message}</span><span className="mono tiny">{j.created_at.slice(0,19).replace('T',' ')}</span></div>)}</div></section>
        </>}
        <footer className="page-footer"><span>MULEGRAPH <i>·</i> EDITORIAL INTELLIGENCE</span><span>CONNECTIONS ARE EVIDENCE. CONTEXT IS ESSENTIAL.</span></footer>
      </main>
    </div>
    {connectionOpen&&<div className="modal-backdrop" onClick={()=>setConnectionOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="connection-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-btn" aria-label="Close connection settings" onClick={()=>setConnectionOpen(false)}><X size={18}/></button><LockKeyhole size={25}/><h2 id="connection-title">Workspace connection</h2><p className="muted">API: {API}</p><label className="field">API access key<input autoFocus type="password" value={apiKey} autoComplete="off" onChange={e=>setApiKey(e.target.value)}/></label><p className="disclaimer">Stored in this tab’s session only. Local development can run without a key; a hosted workspace must be protected. Never commit a key to frontend code.</p><button className="button dark full" onClick={()=>{sessionStorage.setItem('mulegraph-key',apiKey);setError('');setConnectionOpen(false);reload()}}>Save connection <ArrowRight size={14}/></button></section></div>}
  </div>
}
function Metric({n,label,value,detail,icon,accent=false}:{n:string;label:string;value:string;detail:string;icon?:React.ReactNode;accent?:boolean}){return <section className={'metric '+(accent?'accent':'')}><div className="metric-top"><span className="mono tiny">METRIC / {n}</span>{icon}</div><div className="metric-value">{value}</div><span className="mono tiny metric-label">{label}</span><p>{detail}</p></section>}
function PageHeading({overline,title,italic,description}:{overline:string;title:string;italic:string;description:string}){return <div className="page-heading"><span className="eyebrow">{overline}</span><h1>{title} <em>{italic}</em></h1><p>{description}</p></div>}
function MouseHint(){return <GitBranch size={16}/>}
